In [100]:
%pip install numpy pandas seaborn matplotlib

Requirement already satisfied: numpy in /home/lebrancconvas/Project/Code/Side-Project/Data-Project/all-malay/.venv/lib/python3.12/site-packages (2.4.3)
Requirement already satisfied: pandas in /home/lebrancconvas/Project/Code/Side-Project/Data-Project/all-malay/.venv/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: seaborn in /home/lebrancconvas/Project/Code/Side-Project/Data-Project/all-malay/.venv/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: matplotlib in /home/lebrancconvas/Project/Code/Side-Project/Data-Project/all-malay/.venv/lib/python3.12/site-packages (3.10.8)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/lebrancconvas/Project/Code/Side-Project/Data-Project/all-malay/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /home/lebrancconvas/Project/Code/Side-Project/Data-Project/all-malay/.venv/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/lebrancconvas/Project/Code/Side-Project/Data-Project/all-malay/.venv/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/lebrancconvas/Project/Code/Side-Project/Data-Project/all-malay/.venv/lib/python3.12/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/lebrancconvas/Project/Code/Side-Project/Data-Project/all-malay/.venv/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/lebrancconvas/Project/Code/Side-Project/Data-Project/all-malay/.venv/lib/python3.12/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /home/lebrancconvas/Project/Code/Side-Project/Data-Project/all-malay/.venv/lib/python3.12/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /home/lebrancconvas/Project/Code/Side-Project/Data-Project/all-malay/.venv/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /home/lebrancconvas/Project/Code/Side-Project/Data-Project/all-malay/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

# Import Libraries

In [101]:
import pandas as pd   
from pathlib import Path

# Import Data

In [102]:
data_path = Path("../data")
dataset_path = data_path / "dataset"  
output_path = data_path / "output"

In [103]:
file_name = "malaysia_population_by_district"  
population_malaysia_csv_file = dataset_path / f"{file_name}.csv"  
data = pd.read_csv(population_malaysia_csv_file) 
data

,state,district,date,sex,age,ethnicity,population
0,Johor,Batu Pahat,2020-01-01,both,overall,overall,495.3
1,Johor,Batu Pahat,2020-01-01,both,overall,bumi_malay,311.3
2,Johor,Batu Pahat,2020-01-01,both,overall,bumi_other,5.1
3,Johor,Batu Pahat,2020-01-01,both,overall,chinese,140.1
4,Johor,Batu Pahat,2020-01-01,both,overall,indian,6.9
...,...,...,...,...,...,...,...
319195,W.P. Putrajaya,W.P. Putrajaya,2024-01-01,female,65-69,other_noncitizen,0.0
319196,W.P. Putrajaya,W.P. Putrajaya,2024-01-01,female,70-74,other_noncitizen,0.0
319197,W.P. Putrajaya,W.P. Putrajaya,2024-01-01,female,75-79,other_noncitizen,0.0
319198,W.P. Putrajaya,W.P. Putrajaya,2024-01-01,female,80-84,other_noncitizen,0.0
319199,W.P. Putrajaya,W.P. Putrajaya,2024-01-01,female,85+,other_noncitizen,0.0

# EDA

In [104]:
data.columns

Index(['state', 'district', 'date', 'sex', 'age', 'ethnicity', 'population'], dtype='str')

## Issue 01: How about ethnicity in Malaysia (according to this dataset)?

In [105]:
data["ethnicity"].unique()

<StringArray>
[         'overall',       'bumi_malay',       'bumi_other',
          'chinese',           'indian',    'other_citizen',
 'other_noncitizen']
Length: 7, dtype: str

### Answer

Ethnicity in Malaysia in this dataset contains data in structure like this:

- **"overall"**: All ethnicity
- **"bumi_malay"**: Bumiputera Malay or Malaysian Malay 
- **"chinese"**: Malaysian Chinese
- **"indian"**: Malaysian Indian
- **"bumi_other"**: Other Malaysian Bumiputera Ethnicity
- **"other_citizen"**: Other Ethnicity that considered as a Malaysian Citizen.
- **"other_noncitizen"**: Other Ethnicity that not considered as a Malaysian Citizen.

## Issue 02: How about the district and the state in Malaysia?

In [106]:
data["state"].unique()

<StringArray>
[            'Johor',             'Kedah',          'Kelantan',
            'Melaka',   'Negeri Sembilan',            'Pahang',
             'Perak',            'Perlis',      'Pulau Pinang',
             'Sabah',           'Sarawak',          'Selangor',
        'Terengganu', 'W.P. Kuala Lumpur',       'W.P. Labuan',
    'W.P. Putrajaya']
Length: 16, dtype: str

In [107]:
data["district"].unique()

<StringArray>
[       'Batu Pahat',       'Johor Bahru',            'Kluang',
       'Kota Tinggi',             'Kulai',           'Mersing',
              'Muar',           'Pontian',           'Segamat',
           'Tangkak',
 ...
            'Dungun',   'Hulu Terengganu',           'Kemaman',
       'Kuala Nerus',  'Kuala Terengganu',            'Marang',
             'Setiu', 'W.P. Kuala Lumpur',       'W.P. Labuan',
    'W.P. Putrajaya']
Length: 160, dtype: str

In [108]:
state_data = data[["state", "district"]].drop_duplicates()    

state_data_csv_file_path = output_path / "malaysia_state.csv"
state_data.to_csv(state_data_csv_file_path, index=False, encoding="utf-8")

In [109]:
state_data

                   state           district
0                  Johor         Batu Pahat
399                Johor        Johor Bahru
798                Johor             Kluang
1197               Johor        Kota Tinggi
1596               Johor              Kulai
...                  ...                ...
61845         Terengganu             Marang
62244         Terengganu              Setiu
62643  W.P. Kuala Lumpur  W.P. Kuala Lumpur
63042        W.P. Labuan        W.P. Labuan
63441     W.P. Putrajaya     W.P. Putrajaya

[160 rows x 2 columns]

# Data Preparation & Cleansing

In [110]:
print(data)

                 state        district        date     sex      age  \
0                Johor      Batu Pahat  2020-01-01    both  overall
1                Johor      Batu Pahat  2020-01-01    both  overall
2                Johor      Batu Pahat  2020-01-01    both  overall
3                Johor      Batu Pahat  2020-01-01    both  overall
4                Johor      Batu Pahat  2020-01-01    both  overall
...                ...             ...         ...     ...      ...
319195  W.P. Putrajaya  W.P. Putrajaya  2024-01-01  female    65-69
319196  W.P. Putrajaya  W.P. Putrajaya  2024-01-01  female    70-74
319197  W.P. Putrajaya  W.P. Putrajaya  2024-01-01  female    75-79
319198  W.P. Putrajaya  W.P. Putrajaya  2024-01-01  female    80-84
319199  W.P. Putrajaya  W.P. Putrajaya  2024-01-01  female      85+

               ethnicity  population
0                overall       495.3
1             bumi_malay       311.3
2             bumi_other         5.1
3                chinese       140.1
4                 indian         6.9
...                  ...         ...
319195  other_noncitizen         0.0
319196  other_noncitizen         0.0
319197  other_noncitizen         0.0
319198  other_noncitizen         0.0
319199  other_noncitizen         0.0

[319200 rows x 7 columns]

In [111]:
data["state"] = data["state"].replace("Pulau Pinang", "Penang", regex=False)

years = ["2020", "2021", "2022", "2023", "2024"]

for year in years:
    data["date"] = data["date"].replace(f"{year}-01-01", year, regex=False)  

clean_csv_data_file_path = output_path / "malaysia_population_by_district_clean.csv"
data.to_csv(clean_csv_data_file_path, index=False, encoding="utf-8")

In [112]:
data["population"] = data["population"] * 1000  
data["population"] = data["population"].fillna(0).astype("int64")   
data.to_csv(clean_csv_data_file_path, index=False, encoding="utf-8")

# EDA

## Sorting where in Malaysia that has Chinese the most.

In [ ]:
# ethnicity = "chinese"      
states = ["Johor", "Kedah", "Kelantan", "Melaka", "Negeri Sembilan", "Pahang", "Perak", "Perlis", "Penang", "Sabah", "Sarawak", "Selangor", "Terangganu", "W.P. Kuala Lumpur", "W.P. Labuan", "W.P. Putrajaya"]
years = ["2020", "2021", "2022", "2023", "2024"]

for year in years:
  for state in states:
    output_data = data.loc[(data["state"] == state) & (data["sex"] == "both") & (data["age"] == "overall") & (data["date"] == year)]        
    output_data = output_data.drop(labels=["sex", "age"], axis=1, inplace=False)  
    output_data = output_data[output_data["ethnicity"] != "overall"]  
    output_data.sort_values(by=["ethnicity", "population"], ascending=False).to_csv(output_path / year / f"malaysian_{state}_population_{year}.csv", index=False, encoding="utf-8")

In [114]:
data["state"].unique()

<StringArray>
[            'Johor',             'Kedah',          'Kelantan',
            'Melaka',   'Negeri Sembilan',            'Pahang',
             'Perak',            'Perlis',            'Penang',
             'Sabah',           'Sarawak',          'Selangor',
        'Terengganu', 'W.P. Kuala Lumpur',       'W.P. Labuan',
    'W.P. Putrajaya']
Length: 16, dtype: str